[program:cyberphoto-node]
command=/usr/bin/node /www/wwwroot/photogongju/node-server/app.js
directory=/www/wwwroot/photogongju/node-server
autostart=true
autorestart=true
user=www
environment=NODE_ENV=production,PYTHON_API="http://127.0.0.1:7860",PORT=3000
stdout_logfile=/www/wwwroot/photogongju/logs/node.log
stderr_logfile=/www/wwwroot/photogongju/logs/node-error.log
