/**
 * PhotoGongju — Sitemap 自动生成脚本
 *
 * 适配平台:
 *   - 百度搜索资源平台: https://ziyuan.baidu.com/
 *   - Google Search Console: https://search.google.com/
 *   - 360站长平台 / 搜狗站长平台 / 必应站长工具
 *
 * 使用方式:
 *   node scripts/generate-sitemap.js                    # 生成 sitemap.xml
 *   node scripts/generate-sitemap.js --submit           # 生成 + 自动提交到百度
 *
 * 定时执行 (每天凌晨4点):
 *   0 4 * * * node /opt/photogongju/node_web/scripts/generate-sitemap.js >> /var/log/sitemap.log 2>&1
 */

const fs = require('fs');
const path = require('path');
const https = require('https');
const http = require('http');

// ═══════════════════════════════════════════════════════════
// 配置
// ═══════════════════════════════════════════════════════════

const SITE_URL = process.env.SITE_URL || 'https://photogongju.com';
const OUTPUT_DIR = path.join(__dirname, '..', 'public');
const SITEMAP_FILE = path.join(OUTPUT_DIR, 'sitemap.xml');

// 百度站长平台 API 提交密钥
const BAIDU_API_TOKEN = process.env.BAIDU_API_TOKEN || '';

// ═══════════════════════════════════════════════════════════
// 页面定义 — 静态页面 + 动态路由
// ═══════════════════════════════════════════════════════════

const PAGES = [
    // ── 核心工具页面 (高优先级) ──
    { url: '/', changefreq: 'daily', priority: '1.0', desc: '首页-在线证件照制作工具' },
    { url: '/upload', changefreq: 'daily', priority: '0.9', desc: '证件照上传处理' },
    { url: '/size-library', changefreq: 'weekly', priority: '0.8', desc: '证件照尺寸规格大全' },

    // ── 会员与商业页面 (中优先级) ──
    { url: '/membership', changefreq: 'monthly', priority: '0.6', desc: '会员套餐' },

    // ── 教程资讯页 (高收录价值，每周更新) ──
    { url: '/tutorial', changefreq: 'weekly', priority: '0.8', desc: '证件照教程中心' },
    { url: '/tutorial/how-to-take-id-photo', changefreq: 'monthly', priority: '0.7', desc: '在家拍证件照教程' },
    { url: '/tutorial/change-background', changefreq: 'monthly', priority: '0.7', desc: '证件照换底色教程' },
    { url: '/tutorial/photo-resize', changefreq: 'monthly', priority: '0.7', desc: '照片尺寸调整教程' },
    { url: '/tutorial/visa-photo-guide', changefreq: 'monthly', priority: '0.7', desc: '各国签证照片规格指南' },
    { url: '/tutorial/id-photo-print', changefreq: 'monthly', priority: '0.7', desc: '证件照打印排版教程' },
    { url: '/tutorial/ai-background-removal', changefreq: 'monthly', priority: '0.7', desc: 'AI智能抠图教程' },
    { url: '/tutorial/watermark-guide', changefreq: 'monthly', priority: '0.7', desc: '图片水印添加教程' },

    // ── 尺寸规格详情页 (长尾词入口) ──
    { url: '/size-library?id=id_1inch', changefreq: 'monthly', priority: '0.6', desc: '一寸照片尺寸规格' },
    { url: '/size-library?id=id_2inch', changefreq: 'monthly', priority: '0.6', desc: '二寸照片尺寸规格' },
    { url: '/size-library?id=id_passport_cn', changefreq: 'monthly', priority: '0.6', desc: '中国护照照片尺寸' },
    { url: '/size-library?id=id_visa_us', changefreq: 'monthly', priority: '0.6', desc: '美国签证照片尺寸' },
    { url: '/size-library?id=instagram_square', changefreq: 'monthly', priority: '0.5', desc: 'Instagram正方形图片尺寸' },
    { url: '/size-library?id=youtube_thumbnail', changefreq: 'monthly', priority: '0.5', desc: 'YouTube缩略图尺寸' },
    { url: '/size-library?id=taobao_main', changefreq: 'monthly', priority: '0.5', desc: '淘宝商品主图尺寸' },
    { url: '/size-library?id=wechat_moment', changefreq: 'monthly', priority: '0.5', desc: '微信朋友圈图片尺寸' },
    { url: '/size-library?id=xiaohongshu', changefreq: 'monthly', priority: '0.5', desc: '小红书封面尺寸' },

    // ── 文档页 (低优先级) ──
    { url: '/about', changefreq: 'monthly', priority: '0.3', desc: '关于我们' },
];

// ═══════════════════════════════════════════════════════════
// XML 生成
// ═══════════════════════════════════════════════════════════

function generateSitemapXML() {
    const today = new Date().toISOString().split('T')[0];

    let xml = `<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="/sitemap.xsl"?>
<!-- Generated by PhotoGongju Sitemap Generator on ${today} -->
<urlset
    xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"
    xmlns:mobile="http://www.google.com/schemas/sitemap-mobile/1.0"
    xmlns:image="http://www.google.com/schemas/sitemap-image/1.1"
    xmlns:news="http://www.google.com/schemas/sitemap-news/0.9"
    xmlns:video="http://www.google.com/schemas/sitemap-video/1.1"
    xmlns:xhtml="http://www.w3.org/1999/xhtml"
>
`;

    for (const page of PAGES) {
        const fullUrl = SITE_URL + page.url;
        xml += `  <url>
    <loc>${escapeXml(fullUrl)}</loc>
    <lastmod>${today}</lastmod>
    <changefreq>${page.changefreq}</changefreq>
    <priority>${page.priority}</priority>
    <!-- ${escapeXml(page.desc)} -->
  </url>
`;
    }

    xml += `</urlset>`;
    return xml;
}

/**
 * 生成百度专用的 Mobile Sitemap
 */
function generateMobileSitemapXML() {
    const today = new Date().toISOString().split('T')[0];

    let xml = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"
        xmlns:mobile="http://www.google.com/schemas/sitemap-mobile/1.0">
`;

    // 只包含自适应移动端的页面
    const mobilePages = PAGES.filter(p => p.priority >= '0.4');
    for (const page of mobilePages) {
        xml += `  <url>
    <loc>${escapeXml(SITE_URL + page.url)}</loc>
    <mobile:mobile/>
    <lastmod>${today}</lastmod>
    <changefreq>${page.changefreq}</changefreq>
    <priority>${page.priority}</priority>
  </url>
`;
    }

    xml += `</urlset>`;
    return xml;
}

// ═══════════════════════════════════════════════════════════
// 主动提交到百度搜索资源平台
// ═══════════════════════════════════════════════════════════

function submitToBaidu() {
    if (!BAIDU_API_TOKEN) {
        console.log('[百度推送] 跳过: 未配置 BAIDU_API_TOKEN');
        return;
    }

    const urls = PAGES.map(p => SITE_URL + p.url).join('\n');

    const postData = urls;
    const options = {
        hostname: 'data.zz.baidu.com',
        port: 443,
        path: `/urls?site=${encodeURIComponent(SITE_URL)}&token=${BAIDU_API_TOKEN}`,
        method: 'POST',
        headers: {
            'Content-Type': 'text/plain',
            'Content-Length': Buffer.byteLength(postData),
        },
    };

    const req = https.request(options, (res) => {
        let body = '';
        res.on('data', chunk => body += chunk);
        res.on('end', () => {
            try {
                const result = JSON.parse(body);
                if (result.success) {
                    console.log(`[百度推送] 成功: 推送 ${result.success} 条URL, 剩余配额: ${result.remain}`);
                } else {
                    console.log(`[百度推送] 响应: ${body}`);
                }
            } catch {
                console.log(`[百度推送] 响应: ${body}`);
            }
        });
    });

    req.on('error', (e) => console.error(`[百度推送] 错误: ${e.message}`));
    req.write(postData);
    req.end();
}

/**
 * 提交到 Google (通过 ping 方式)
 */
function pingGoogle() {
    const sitemapUrl = `${SITE_URL}/sitemap.xml`;
    const pingUrl = `http://www.google.com/ping?sitemap=${encodeURIComponent(sitemapUrl)}`;

    http.get(pingUrl, (res) => {
        console.log(`[Google Ping] 状态码: ${res.statusCode}`);
    }).on('error', (e) => {
        console.error(`[Google Ping] 错误: ${e.message}`);
    });
}

// ═══════════════════════════════════════════════════════════
// 写入文件
// ═══════════════════════════════════════════════════════════

function writeSitemapFiles() {
    // 确保输出目录存在
    if (!fs.existsSync(OUTPUT_DIR)) {
        fs.mkdirSync(OUTPUT_DIR, { recursive: true });
    }

    // 主 Sitemap
    const xml = generateSitemapXML();
    fs.writeFileSync(SITEMAP_FILE, xml, 'utf8');
    console.log(`[Sitemap] 已生成: ${SITEMAP_FILE} (${PAGES.length} 个URL)`);

    // 百度移动适配 Sitemap
    const mobileXml = generateMobileSitemapXML();
    const mobileFile = path.join(OUTPUT_DIR, 'sitemap-mobile.xml');
    fs.writeFileSync(mobileFile, mobileXml, 'utf8');
    console.log(`[Sitemap] 移动适配: ${mobileFile}`);

    // 生成 Sitemap 索引文件
    const today = new Date().toISOString().split('T')[0];
    const indexXml = `<?xml version="1.0" encoding="UTF-8"?>
<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
  <sitemap><loc>${SITE_URL}/sitemap.xml</loc><lastmod>${today}</lastmod></sitemap>
  <sitemap><loc>${SITE_URL}/sitemap-mobile.xml</loc><lastmod>${today}</lastmod></sitemap>
</sitemapindex>`;
    const indexFile = path.join(OUTPUT_DIR, 'sitemap-index.xml');
    fs.writeFileSync(indexFile, indexXml, 'utf8');
    console.log(`[Sitemap] 索引文件: ${indexFile}`);
}

// ═══════════════════════════════════════════════════════════
// 工具函数
// ═══════════════════════════════════════════════════════════

function escapeXml(str) {
    return str
        .replace(/&/g, '&amp;')
        .replace(/</g, '&lt;')
        .replace(/>/g, '&gt;')
        .replace(/"/g, '&quot;')
        .replace(/'/g, '&apos;');
}

// ═══════════════════════════════════════════════════════════
// 主入口
// ═══════════════════════════════════════════════════════════

function main() {
    console.log('═'.repeat(50));
    console.log('  PhotoGongju Sitemap 生成工具');
    console.log(`  站点: ${SITE_URL}`);
    console.log(`  时间: ${new Date().toISOString()}`);
    console.log('═'.repeat(50));
    console.log('');

    // 1. 生成 Sitemap 文件
    writeSitemapFiles();

    // 2. 自动提交
    const args = process.argv.slice(2);
    if (args.includes('--submit') || args.includes('-s')) {
        console.log('\n--- 主动推送 ---');
        submitToBaidu();
        pingGoogle();
    }

    // 3. 打印提交指引
    console.log('\n📋 手动提交指引:');
    console.log(`  百度: https://ziyuan.baidu.com/linksubmit/url → 提交 ${SITE_URL}/sitemap.xml`);
    console.log(`  Google: https://search.google.com/search-console → 提交 ${SITE_URL}/sitemap.xml`);
    console.log(`  360: https://zhanzhang.so.com/ → 提交 ${SITE_URL}/sitemap.xml`);
    console.log(`  必应: https://www.bing.com/webmasters/ → 提交 ${SITE_URL}/sitemap.xml`);
    console.log('');
}

main();
